data.img_h: 256
data.img_w: 384
data.name: realestate10k
data.per_gpu_batch_size: 4
data.training_set_path: TRAINING_SET_PATH 
data.val_set_path: VAL_SET_PATH 
data.visible_point_count: 256
lr.backbone_lr: 0.0002
lr.decay_gamma: 0.1
lr.decay_steps: 4,8
lr.decoder_lr: 0.001
lr.weight_decay: 4.0e-05
loss.smoothness_lambda_v1: 0.5
loss.smoothness_gmin: 2.0
loss.smoothness_grad_ratio: 0.1
training.epochs: 10
training.eval_interval: 10000 
