data.img_h: 256
data.img_w: 384
data.name: dtu
data.per_gpu_batch_size: 8
data.training_set_path: /data00/home/jiaxinli/data/dtu_3
data.val_set_path: /data00/home/jiaxinli/data/dtu_3
data.visible_point_count: 256
data.rotation_pi_ratio: 3
data.is_exclude_views: false
model.decoder_type: batch_decoder
lr.backbone_lr: 0.0002
lr.decay_gamma: 0.1
lr.decay_steps: 60, 120
lr.decoder_lr: 0.001
lr.weight_decay: 4.0e-05
mpi.disparity_end: 0.1
mpi.disparity_start: 1.0
mpi.num_bins_coarse: 32
mpi.fix_disparity: false
mpi.valid_mask_threshold: 0
mpi.is_bg_depth_inf: true
loss.smoothness_lambda_v1: 0.0
loss.smoothness_gmin: 2.0
loss.smoothness_grad_ratio: 0.1
loss.smoothness_lambda_v2: 0.01
training.epochs: 200
training.eval_interval: 1000
training.gpus: 1,2,3,4,5,6,7
training.src_rgb_blending: true
