data.img_h: 384
data.img_w: 512 
data.name: flowers 
data.per_gpu_batch_size: 2
data.training_set_path: TRAINING_SET_PATH 
data.val_set_path: VAL_SET_PATH 
lr.backbone_lr: 0.0002
lr.decay_gamma: 0.1
lr.decay_steps: 5,10,15
lr.decoder_lr: 0.001
lr.weight_decay: 4.0e-05
mpi.disparity_end: 0.03
mpi.disparity_start: 3.0
training.epochs: 20
training.eval_interval: 4000 
